notes/noteapp/urls.py
from django.urls import path
from . import views

app_name = 'noteapp'

urlpatterns = [
    path('', views.main, name='main'),
    path('note/', views.note, name='note'),
    path('tag/', views.tag, name='tag'),
    path('author/', views.author, name='author'),
    path('author/<int:author_id>/', views.author_detail, name='author_detail'),
]

notes/notes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('noteapp.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notes/users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

notes/noteapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Tag(models.Model):
    name = models.CharField(max_length=25, null=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'name'], name='tag of username')
        ]

    def __str__(self):
        return f"{self.name}"


class Author(models.Model):
    fullname = models.CharField(null=False)
    born_date = models.CharField(null=False)
    born_location = models.CharField(null=False)
    description = models.CharField(null=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return f"{self.fullname}"


class Note(models.Model):
    quote = models.CharField(null=False)
    tags = models.CharField(blank=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return f"{self.quote}"

notes/noteapp/forms.py
from django.forms import ModelForm, CharField, TextInput
from .models import Tag, Note, Author


class TagForm(ModelForm):
    name = CharField(min_length=3, max_length=25, required=True, widget=TextInput())

    class Meta:
        model = Tag
        fields = ['name']


class AuthorForm(ModelForm):
    fullname = CharField(min_length=3, max_length=25, required=True, widget=TextInput())
    born_date = CharField(min_length=3, max_length=25, required=True, widget=TextInput())
    born_location = CharField(min_length=3, max_length=25, required=True, widget=TextInput())
    description = CharField(required=True, widget=TextInput())

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']


class NoteForm(ModelForm):

    quote = CharField(min_length=3, max_length=500, required=True, widget=TextInput())

    class Meta:
        model = Note
        fields = ['quote']
        exclude = ['tags', 'authors']

notes/noteapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from .forms import TagForm, NoteForm, Tag, Note, AuthorForm
from .models import Author


# Create your views here.
def main(request):
    notes = Note.objects.all()
    return render(request, 'noteapp/index.html', {"notes": notes})


def author_detail(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    return render(request, 'noteapp/author_detail.html', {'author': author})


@login_required
def tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            tag = form.save(commit=False)
            tag.user = request.user
            tag.save()
            return redirect(to='noteapp:main')
        else:
            return render(request, 'noteapp/tag.html', {'form': form})

    return render(request, 'noteapp/tag.html', {'form': TagForm()})


@login_required
def author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            author = form.save(commit=False)
            author.user = request.user
            author.save()
            return redirect(to='noteapp:main')
        else:
            return render(request, 'noteapp/author.html', {'form': form})

    return render(request, 'noteapp/author.html', {'form': AuthorForm()})

@login_required
def note(request):
    tags = Tag.objects.all()
    authors = Author.objects.all()

    if request.method == 'POST':
        form = NoteForm(request.POST)
        if form.is_valid():
            new_note = form.save(commit=False)
            new_note.user = request.user
            author_id = request.POST.get('author_id')
            author = get_object_or_404(Author, pk=author_id)
            new_note.author = author

            new_note.save()
            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'), user=request.user)
            for tag in choice_tags.iterator():
                new_note.tags.add(tag)

            return redirect(to='noteapp:main')
        else:
            return render(request, 'noteapp/note.html', {"authors": authors, "tags": tags, 'form': form})

    return render(request, 'noteapp/note.html', {"tags": tags, "authors": authors, 'form': NoteForm()})





@login_required
def detail(request, note_id):
    note = get_object_or_404(Note, pk=note_id, user=request.user)
    return render(request, 'noteapp/detail.html', {"note": note})


@login_required
def set_done(request, note_id):
    Note.objects.filter(pk=note_id, user=request.user).update(done=True)
    return redirect(to='noteapp:main')


@login_required
def delete_note(request, note_id):
    Note.objects.get(pk=note_id, user=request.user).delete()
    return redirect(to='noteapp:main')

notes/noteapp/templates/noteapp/author.html
{% extends "noteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'noteapp:author' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Enter the author fullname:
            {{ form.fullname }}
        </label>
        <span>{{ form.errors.fullname }}</span>
    </div>
    <div style="padding: 10px">
        <label> Enter the author's birthdate:
            {{ form.born_date }}
        </label>
        <span>{{ form.errors.born_date }}</span>
    </div>
    <div style="padding: 10px">
        <label> Enter the author's born location:
            {{ form.born_location }}
        </label>
        <span>{{ form.errors.born_location }}</span>
    </div>
    <div style="padding: 10px">
        <label> Enter the author's descriptions:
            {{ form.description }}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>

    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

notes/noteapp/templates/noteapp/author_detail.html
{% extends "noteapp/base.html" %}

{% block content %}

<h1>{{ author.fullname }}</h1>
<p>Born Date: <b>{{ author.born_date }}</b></p>
<p>Born Location: <b>{{ author.born_location }}</b></p>
<p>Description: <b>{{ author.description }}</b></p>

{% endblock %}

notes/noteapp/templates/noteapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Quotes</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
    {% load static %}
    <link rel="stylesheet" href="{% static 'noteapp/style.css' %}">
</head>
<body>
<main class="container">
    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
        <ul>
            <li><a href="/" role="button"> Go back to the main page </a></li>
        </ul>
    </nav>
    {% block content %} {% endblock %}
</main>
</body>
</html>

notes/noteapp/templates/noteapp/detail.html
{% extends "noteapp/base.html" %} {% load extract_tags %} {% load extract_authors %} {% block content %}

<h1>{{note.name}}</h1>
<p>Description: <b>{{note.description}}</b></p>
<p>Time of creation: <kbd>{{note.created}}</kbd></p>
{% if note.done %}
<p>
  Status:
  <ins>Completed</ins>
</p>
{% else %}
<p>Status: <i>Not implemented</i></p>
{% endif %}

<p>Authors: <small> {{ note.authors|authors }} </small></p>
<p>Tags: <small> {{ note.tags|tags }} </small></p>
{% endblock %}

notes/noteapp/templates/noteapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Quotes</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
</head>
<body>
<main class="container">
<nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
    {% if user.is_authenticated %}
    <ul>
        <li><a href="{% url 'noteapp:author' %}" role="button">Add Author</a></li>
        <li><a href="{% url 'noteapp:note' %}" role="button">Add quote</a></li>
    </ul>
    <ul>
        <li>Welcome <b>{{ user.username }}!</b></li>
        <li><a href="{% url 'users:profile' %}" role="button">Profile</a></li>
        <li><a href="{% url 'users:logout' %}" role="button">Logout</a></li>
    </ul>
    {% else %}
    <ul>
        <li><a href="{% url 'users:signup' %}" role="button">Sign Up</a></li>
        <li><a href="{% url 'users:login' %}" role="button">Login</a></li>
    </ul>
    {% endif %}
</nav>
    {% for note in notes %}
    <ul>
        <li>{{ note.quote }}</li>
        <li>Author: <a href="{% url 'noteapp:author_detail' note.author.pk %}">{{ note.author.fullname }}</a></li>
    </ul>
    {% endfor %}
</main>
</body>
</html>

notes/noteapp/templates/noteapp/note.html
{% extends "noteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'noteapp:note' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Quote:
            {{ form.quote }}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div style="padding: 10px">
        <label> Select authors:
            <select name="author_id" id="author_id">
                {% for author in authors %}
                <option value="{{ author.pk }}">{{ author.fullname }}</option>
                {% endfor %}
            </select>
        </label>
    </div>
<!--    <div style="padding: 10px">-->
<!--        <label> Select tags:-->
<!--            <select name="tags" multiple="multiple" required>-->
<!--                {% for tag in tags %}-->
<!--                <option value="{{tag.pk}}">{{tag.name}}</option>-->
<!--                {% endfor %}-->
<!--            </select>-->
<!--        </label>-->
<!--    </div>-->
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

notes/noteapp/templates/noteapp/quotes.html
{% extends "noteapp/base.html" %} {% load extract_quotes %} {% load extract_authors %} {% block content %}

<h1>{{note.name}}</h1>
<p>Description: <b>{{note.description}}</b></p>
<p>Time of creation: <kbd>{{note.created}}</kbd></p>
{% if note.done %}
<p>
  Status:
  <ins>Completed</ins>
</p>
{% else %}
<p>Status: <i>Not implemented</i></p>
{% endif %}

<p>Authors: <small> {{ note.authors|authors }} </small></p>
<p>Tags: <small> {{ note.tags|tags }} </small></p>
{% endblock %}

notes/noteapp/templates/noteapp/tag.html
{% extends "noteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'noteapp:tag' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the tag name:
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}